name: Denopendabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
